extends: default
ignore: |
  vendor/
  node_modules/
rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  empty-lines:
    max: 2
  truthy:
    allowed-values: ["true", "false"]
  document-start: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 2
