import type { DemoAnswers, DemoData, DemoFile, TreeNode } from "./demo-types";

function toSnakeCase(name: string): string {
  return name.replace(/-/g, "_");
}

function generateProfileYaml(answers: DemoAnswers): string {
  const { projectType, deployMode, repoName, repoName2 } = answers;

  const modeComments: Record<string, string> = {
    override:
      "# Override mode: replaces any existing CLAUDE.md with your managed rules",
    merge:
      "# Merge mode: appends your rules after the repo's existing CLAUDE.md",
    ghost:
      "# Ghost mode: like merge, but all generated files are gitignored",
  };

  const lines: string[] = [modeComments[deployMode], "profiles:"];

  if (projectType === "single") {
    lines.push("  my-stack:");
    lines.push('    description: "Your development standards"');
    if (deployMode === "merge" || deployMode === "ghost") {
      lines.push("    append: true");
    }
    if (deployMode === "ghost") {
      lines.push("    gitignore: true");
    }
    lines.push("    files:");
    lines.push("      - /path/to/rules/code-review.md");
    lines.push("      - /path/to/rules/testing-patterns.md");
    lines.push("      - /path/to/rules/commit-conventions.md");
    lines.push("    skills:");
    lines.push("      - /path/to/rules/skills/debugging/");
    lines.push("    mcp_servers:");
    lines.push("      - playwright");
  } else {
    const repo1Snake = toSnakeCase(repoName);
    const repo2Snake = repoName2 ? toSnakeCase(repoName2) : "repo2";

    lines.push("  orchestrator:");
    lines.push('    description: "Multi-repo dispatcher"');
    lines.push("    files:");
    lines.push("      - /path/to/rules/dispatch.md");
    lines.push("    subagents:");
    lines.push(`      - name: ${repo1Snake}`);
    lines.push(`        profile: ${repoName}`);
    lines.push(`        cwd: ${repoName}`);
    if (deployMode === "merge" || deployMode === "ghost") {
      lines.push("        append: true");
    }
    lines.push(`      - name: ${repo2Snake}`);
    lines.push(`        profile: ${repoName2 || "repo2"}`);
    lines.push(`        cwd: ${repoName2 || "repo2"}`);
    if (deployMode === "merge" || deployMode === "ghost") {
      lines.push("        append: true");
    }
    if (deployMode === "ghost") {
      lines.push("    gitignore: true");
    }
    lines.push("    mcp_servers:");
    lines.push("      - playwright");
    lines.push("      - teams");
  }

  return lines.join("\n");
}

function generateClaudeLocalMd(answers: DemoAnswers): string {
  const modeNotes: Record<string, string> = {
    override:
      "<!-- Generated by ruly squash (override mode) — this file replaces CLAUDE.md -->",
    merge:
      "<!-- Generated by ruly squash (merge mode) — appended after existing CLAUDE.md -->",
    ghost:
      "<!-- Generated by ruly squash (ghost mode) — gitignored, appended after existing CLAUDE.md -->",
  };

  return `${modeNotes[answers.deployMode]}

# Code Review Standards

- All PRs require at least one approval before merge
- Use conventional commit messages (feat:, fix:, chore:, etc.)
- Keep PRs focused — one concern per PR

# Testing Patterns

- Write tests before marking a task as complete
- Unit tests for business logic, integration tests for API endpoints
- Use factories instead of fixtures for test data

# Commit Conventions

- Prefix commits with type: feat, fix, chore, docs, test, refactor
- Keep subject line under 72 characters
- Reference issue numbers in commit body when applicable`;
}

function generateMcpJson(): string {
  return JSON.stringify(
    {
      mcpServers: {
        playwright: {
          command: "npx",
          args: ["-y", "@anthropic/playwright-mcp"],
        },
        teams: {
          command: "npx",
          args: ["-y", "@anthropic/mcp-teams"],
        },
      },
    },
    null,
    2
  );
}

function generateExistingClaudeMd(repoName: string): string {
  return `# ${repoName}

## Project Setup

- Run \`npm install\` to install dependencies
- Use \`npm run dev\` for local development
- See docs/ for architecture decisions

## Code Style

- Follow the existing patterns in the codebase
- Use TypeScript strict mode
- Prefer functional components`;
}

function generateAgentMd(repoName: string): string {
  return `---
description: "Engineer for ${repoName}"
---

# ${repoName} Engineer

You work in the ${repoName} repository.

## Responsibilities

- Implement features and fix bugs in ${repoName}
- Follow the repository's coding standards
- Run tests before committing changes`;
}

function generateGitignore(): string {
  return `CLAUDE.local.md
.claude/settings.local.json
.mcp.json`;
}

function buildTree(answers: DemoAnswers): TreeNode {
  const { projectType, deployMode, repoName, repoName2 } = answers;

  const claudeMdComment =
    deployMode === "override"
      ? "Ignored — overridden by your rules"
      : "Existing repo rules (preserved)";
  const claudeMdDimmed = deployMode === "override";

  if (projectType === "single") {
    const children: TreeNode[] = [
      {
        name: "CLAUDE.local.md",
        type: "file",
        fileKey: "claude-local",
        comment: "Generated rules",
      },
      {
        name: ".mcp.json",
        type: "file",
        fileKey: "mcp-json",
        comment: "MCP server configuration",
      },
      {
        name: ".claude",
        type: "directory",
        children: [
          {
            name: "skills",
            type: "directory",
            children: [
              {
                name: "debugging",
                type: "directory",
                comment: "Debugging skills",
              },
            ],
          },
          {
            name: "settings.local.json",
            type: "file",
            comment: "Local settings",
          },
        ],
      },
      {
        name: "CLAUDE.md",
        type: "file",
        fileKey: "existing-claude-md",
        comment: claudeMdComment,
        dimmed: claudeMdDimmed,
      },
    ];

    if (deployMode === "ghost") {
      children.push({
        name: ".gitignore",
        type: "file",
        fileKey: "gitignore",
        comment: "Keeps generated files out of git",
      });
    }

    return {
      name: `${repoName}/`,
      type: "directory",
      children,
    };
  }

  // Multi-repo
  const repo2 = repoName2 || "repo2";
  const repo1Snake = toSnakeCase(repoName);
  const repo2Snake = toSnakeCase(repo2);

  const children: TreeNode[] = [
    {
      name: "CLAUDE.local.md",
      type: "file",
      fileKey: "claude-local",
      comment: "Generated orchestrator rules",
    },
    {
      name: ".mcp.json",
      type: "file",
      fileKey: "mcp-json",
      comment: "MCP servers (collected from subagents)",
    },
    {
      name: ".claude",
      type: "directory",
      children: [
        {
          name: "agents",
          type: "directory",
          children: [
            {
              name: `${repo1Snake}.md`,
              type: "file",
              fileKey: "agent-1",
              comment: `Agent for ${repoName}`,
            },
            {
              name: `${repo2Snake}.md`,
              type: "file",
              fileKey: "agent-2",
              comment: `Agent for ${repo2}`,
            },
          ],
        },
        {
          name: "settings.local.json",
          type: "file",
          comment: "Local settings",
        },
      ],
    },
    {
      name: repoName,
      type: "directory",
      comment: "Repository (git submodule)",
      children: [
        {
          name: "CLAUDE.md",
          type: "file",
          fileKey: "existing-claude-md",
          comment: claudeMdComment,
          dimmed: claudeMdDimmed,
        },
      ],
    },
    {
      name: repo2,
      type: "directory",
      comment: "Repository (git submodule)",
      children: [
        {
          name: "CLAUDE.md",
          type: "file",
          fileKey: "existing-claude-md-2",
          comment: claudeMdComment,
          dimmed: claudeMdDimmed,
        },
      ],
    },
  ];

  if (deployMode === "ghost") {
    children.push({
      name: ".gitignore",
      type: "file",
      fileKey: "gitignore",
      comment: "Keeps generated files out of git",
    });
  }

  return {
    name: "orchestrator/",
    type: "directory",
    children,
  };
}

export function generateDemoData(answers: DemoAnswers): DemoData {
  const { projectType, repoName, repoName2 } = answers;
  const repo2 = repoName2 || "repo2";

  const files: Record<string, DemoFile> = {
    "profile-yaml": {
      path: "profiles.yml",
      content: generateProfileYaml(answers),
      language: "yaml",
    },
    "claude-local": {
      path: "CLAUDE.local.md",
      content: generateClaudeLocalMd(answers),
      language: "markdown",
    },
    "mcp-json": {
      path: ".mcp.json",
      content: generateMcpJson(),
      language: "json",
    },
    "existing-claude-md": {
      path: `${projectType === "multi" ? repoName + "/" : ""}CLAUDE.md`,
      content: generateExistingClaudeMd(repoName),
      language: "markdown",
    },
  };

  if (projectType === "multi") {
    files["existing-claude-md-2"] = {
      path: `${repo2}/CLAUDE.md`,
      content: generateExistingClaudeMd(repo2),
      language: "markdown",
    };
    files["agent-1"] = {
      path: `.claude/agents/${toSnakeCase(repoName)}.md`,
      content: generateAgentMd(repoName),
      language: "markdown",
    };
    files["agent-2"] = {
      path: `.claude/agents/${toSnakeCase(repo2)}.md`,
      content: generateAgentMd(repo2),
      language: "markdown",
    };
  }

  if (answers.deployMode === "ghost") {
    files["gitignore"] = {
      path: ".gitignore",
      content: generateGitignore(),
      language: "bash",
    };
  }

  const tree = buildTree(answers);

  return {
    tree,
    files,
    initialFileKey: "profile-yaml",
  };
}
