# frozen_string_literal: true

require 'tiktoken_ruby'

module Ruly
  module Operations
    # Generate token statistics for rule files
    class Stats < Base
      attr_reader :sources, :output_file

      # @param sources [Array<Hash>] Array of source hashes with :path and :type keys
      # @param output_file [String] Path to output markdown file
      def initialize(sources:, output_file: 'stats.md')
        super()
        @sources = sources
        @output_file = output_file
      end

      def call
        file_stats = build_file_stats
        write_markdown(file_stats)

        build_result(
          success: true,
          data: {
            file_count: file_stats.size,
            files: file_stats,
            output_file:,
            total_tokens: file_stats.sum { |f| f[:tokens] }
          }
        )
      rescue StandardError => e
        build_result(success: false, error: e.message)
      end

      # Build stats without writing to file (useful for testing)
      def build_file_stats
        file_stats = []

        sources.each do |source|
          next unless source[:type] == 'local'

          file_path = source[:path]
          next unless file_path && File.exist?(file_path)

          content = File.read(file_path, encoding: 'UTF-8')
          tokens = count_tokens(content)
          file_stats << {
            path: file_path,
            size: content.bytesize,
            tokens:
          }
        end

        # Sort by token count descending
        file_stats.sort_by { |f| -f[:tokens] }
      end

      private

      def write_markdown(file_stats)
        total_tokens = file_stats.sum { |f| f[:tokens] }
        total_size = file_stats.sum { |f| f[:size] }

        File.open(output_file, 'w') do |f|
          write_header(f, file_stats.size, total_tokens, total_size)
          write_table(f, file_stats)
          write_footer(f)
        end
      end

      def write_header(file, file_count, total_tokens, total_size)
        file.puts '# Ruly Token Statistics'
        file.puts
        file.puts "Generated: #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}"
        file.puts
        file.puts '## Summary'
        file.puts
        file.puts "- **Total Files**: #{file_count}"
        file.puts "- **Total Tokens**: #{format_number(total_tokens)}"
        file.puts "- **Total Size**: #{format_bytes(total_size)}"
        file.puts
      end

      def write_table(file, file_stats)
        file.puts '## Files by Token Count'
        file.puts
        file.puts '| # | Tokens | Size | File |'
        file.puts '|--:|-------:|-----:|:-----|'

        file_stats.each_with_index do |stat, idx|
          file.puts "| #{idx + 1} | #{format_number(stat[:tokens])} | #{format_bytes(stat[:size])} | `#{stat[:path]}` |"
        end

        file.puts
      end

      def write_footer(file)
        file.puts '---'
        file.puts '*Generated by [ruly](https://github.com/patrickclery/ruly)*'
      end

      def count_tokens(text)
        encoder = Tiktoken.get_encoding('cl100k_base')
        utf8_text = text.encode('UTF-8', invalid: :replace, replace: '?', undef: :replace)
        encoder.encode(utf8_text).length
      end

      def format_number(num)
        num.to_s.gsub(/(\d)(?=(\d{3})+(?!\d))/, '\\1,')
      end

      def format_bytes(bytes)
        if bytes >= 1_048_576
          "#{(bytes / 1_048_576.0).round(1)} MB"
        elsif bytes >= 1024
          "#{(bytes / 1024.0).round(1)} KB"
        else
          "#{bytes} B"
        end
      end
    end
  end
end
