"use client";

import { useState } from "react";
import { DemoData } from "@/lib/demo-types";
import FileTree from "@/components/FileTree";
import FilePreview from "@/components/FilePreview";

interface ExplorerProps {
  data: DemoData;
}

export default function Explorer({ data }: ExplorerProps) {
  const [selectedFileKey, setSelectedFileKey] = useState<string>(data.initialFileKey);

  const selectedFile = selectedFileKey ? (data.files[selectedFileKey] ?? null) : null;

  return (
    <div className="rounded-lg border border-gray-700 bg-gray-950 font-mono text-sm shadow-2xl">
      {/* Title bar */}
      <div className="flex items-center gap-3 border-b border-gray-700 px-4 py-3">
        <div className="flex gap-2">
          <div className="h-3 w-3 rounded-full bg-red-500" />
          <div className="h-3 w-3 rounded-full bg-yellow-500" />
          <div className="h-3 w-3 rounded-full bg-green-500" />
        </div>
        <span className="text-xs text-gray-400">
          {data.tree.name} — generated by ruly
        </span>
      </div>

      {/* Two-panel layout */}
      <div className="flex h-[500px]">
        {/* Left sidebar */}
        <div className="w-64 shrink-0 border-r border-gray-700 overflow-y-auto">
          <div className="px-4 py-2 text-xs uppercase text-gray-500">
            Explorer
          </div>
          <div className="px-2 pb-2 text-xs">
            <FileTree
              tree={data.tree}
              onFileClick={setSelectedFileKey}
              selectedFileKey={selectedFileKey}
            />
          </div>
        </div>

        {/* Right main panel */}
        <div className="flex-1 min-w-0">
          <FilePreview file={selectedFile} />
        </div>
      </div>
    </div>
  );
}
